Feature/#9
conea0/course-library-cli pull request #19
Opened 2023-11-01 22:35 UTC by iwbchi

Testとpyコードを受け取ってOutputを書き換える関数の作成

2023-11-01 23:30 UTC, syuya2036 requested changes

2023-11-01 23:30 UTC, syuya2036 commented on problems/testcase.go
> +		// stdin.Write([]byte(str))
不要なコメントは削除しましょう。

2023-11-02 01:39 UTC, iwbchi commented on problems/testcase.go
> +		// stdin.Write([]byte(str))
コメント編集しました

2023-11-02 01:40 UTC, syuya2036 approved these changes
lgtm✨

2023-11-02 01:40 UTC, merged